description: Develop and publish Web APIs based on Java Stack for Cloud Native environments with Spring Boot and other Spring technologies.
name: graphene-java-api-stack
display-name: Stack Web API with Spring Boot
picture: stack.png
category: Backend; # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - java
  - spring
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - docker
  - java
  - gradle
about: docs/about.md
use-cases:
  - title: REST API Web Service
    content: docs/use-case.md
    stackfile: stackfiles/default.yaml
  - title: REST API Web Service with metrics and tracing
    content: docs/use-case.md
    stackfile: stackfiles/observability.yaml
  - title: REST API Web Service with database relational
    content: db-relational-plugin/docs/use-case.md
    stackfile: stackfiles/db-relational.yaml