name: tracing-plugin
description: This plugin adds functionalities to trace the application using Jaeger.
display-name: Tracing
picture: plugin.png
category: backend
compatibility:
  - java
  - spring
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies:
  - "Api"
types:
  - app
hooks:
  - type: run-script
    trigger: before-render
    script: ../common_scripts/hooks/asking_for_required_information.py
  - type: edit
    trigger: after-render
    path: build.gradle
    changes:
      - search:
          string: "dependencies {"
          insert-after:
            snippet: snippets/tracing-dependencies-gradle.txt
          when:
            not-exists-snippet: snippets/tracing-dependencies-gradle.txt
    condition:
      variable: build_tool
      operator: ==
      value: Gradle
  - type: edit-xml
    trigger: after-render
    path: pom.xml
    changes:
      - xpath: "dependencies"
        append:
          snippet: snippets/tracing-dependencies-maven.xml
        when:
          not-exists: ./dependencies/dependency/groupId[.='io.opentracing.contrib']/../artifactId[.='opentracing-spring-jaeger-starter']
    condition:
      variable: build_tool
      operator: ==
      value: Maven
