name: tracing-plugin
description: Plugin para configuração de Tracing
display-name: Tracing
picture: plugin.png
category: backend
compatibility:
  - java
  - spring
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies:
  - "Api"
types:
  - app
hooks:
  - type: run
    trigger: after-render
    working-dir: "{{project_name}}"
    linux:
      - chmod 755 gradlew
      - gradlew addDep --dep OPENTRACING_JAEGER
    windows:
      - gradlew.bat addDep --dep OPENTRACING_JAEGER
    mac:
      - chmod 755 gradlew
      - gradlew addDep --dep OPENTRACING_JAEGER

