version: '3.3'
services:
  ms-{{project_artifact_id}}:
    image: {{project_artifact_id}}
    restart: always
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE:
    ports:
      - "8080:8080"
    build: .
    networks:
      - app-{{project_artifact_id}}
networks:
  app-{{project_artifact_id}}:
    driver: bridge

