  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql-server:5432/test
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
