name: logging-plugin
description: This plugin gives a pre-configured structure log in JSON format.
display-name: Logging
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - java
  - spring
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - java
  - spring
types:
  - app
hooks:
  - type: run-script
    trigger: before-render
    script: ../common_scripts/hooks/asking_for_required_information.py
  - type: edit
    trigger: after-render
    path: build.gradle
    changes:
      - search:
          string: "dependencies {"
          insert-after:
            snippet: snippets/logging-dependencies-gradle.txt
          when:
            not-exists-snippet: snippets/logging-dependencies-gradle.txt
    condition:
      variable: build_tool
      operator: ==
      value: Gradle
  - type: edit-xml
    trigger: after-render
    path: pom.xml
    changes:
      - xpath: .//dependencies
        append:
          snippet: snippets/logging-dependencies-maven.txt
        when:
          not-exists: ./dependencies/dependency/groupId[.='net.logstash.logback']/../artifactId[.='logstash-logback-encoder']
    condition:
      variable: build_tool
      operator: ==
      value: Maven



