  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb-server:3306/test
    username: admin
    password: admin123
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
