name: metrics-plugin
description: This plugin adds functionalities to obtain the application's metrics using the Spring Actuator component.
display-name: Metrics
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - java
  - spring
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - java
  - spring
types:
  - app
inputs:
  - label: Enter the base package for the project
    type: text
    name: project_group_id
    pattern: '(^[a-zA-Z_\d.]*)'
    default: br.com.graphene
    global: true
  - label: Select the project build tool
    type: text
    items:
      - Maven
      - Gradle
    default: Maven
    name: build_tool
    global: true
hooks:
  - type: edit
    trigger: after-render
    path: build.gradle
    changes:
      - search:
          string: "dependencies {"
          insert-after:
            snippet: snippets/metrics-dependencies-gradle.txt
          when:
            not-exists-snippet: snippets/metrics-dependencies-gradle.txt
    condition:
      variable: build_tool
      operator: ==
      value: Gradle
  - type: edit-xml
    trigger: after-render
    path: pom.xml
    changes:
      - xpath: "dependencies/dependency[artifactId='spring-boot-starter-actuator']"
        clear: true
    condition:
      variable: build_tool
      operator: ==
      value: Maven
  - type: edit
    trigger: after-render
    path: pom.xml
    changes:
      - search:
          string: "<dependency />"
          replace-by:
            value: " "
    condition:
      variable: build_tool
      operator: ==
      value: Maven
  - type: edit-xml
    trigger: after-render
    path: pom.xml
    changes:
      - xpath: "dependencies"
        append:
          snippet: snippets/metrics-dependencies-maven.xml
#          Add in future version of CLI
#          when:
#            not-exists-snippet: snippets/metrics-dependencies-maven.xml
    condition:
      variable: build_tool
      operator: ==
      value: Maven
