name: metrics-plugin
description: This plugin adds functionalities to obtain the application's metrics using the Spring Actuator component.
display-name: Metrics
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - java
  - spring
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - java
  - spring
types:
  - app
hooks:
  - type: run-script
    trigger: before-render
    script: ../common_scripts/hooks/asking_for_required_information.py
  - type: edit
    trigger: after-render
    path: build.gradle
    changes:
      - search:
          string: "dependencies {"
          insert-after:
            snippet: snippets/metrics-dependencies-gradle.txt
          when:
            not-exists-snippet: snippets/metrics-dependencies-gradle.txt
    condition:
      variable: build_tool
      operator: ==
      value: Gradle
  - type: edit-xml
    trigger: after-render
    path: pom.xml
    changes:
      - xpath: "dependencies"
        append:
          snippet: snippets/metrics-dependencies-maven.xml
        when:
          not-exists: ./dependencies/dependency/groupId[.='org.springframework.boot']/../artifactId[.='spring-boot-starter-actuator']
    condition:
      variable: build_tool
      operator: ==
      value: Maven
